### ISSUE TITLE
jupyter use demo? or maybe better as an external link

### ISSUE THREAD

**Issue by elliewix** [data-lessons/library-python-intro#33]
Is it possible to embed a gif of Jupyter use or link to a short demo on youtube for those who might not have the benefit of in person instruction?  I find the block of text to be a lot to parse through.  

Alternatively, it might be worthwhile to find a Jupyter Project link to for these directions. Having them so detailed in this lesson means that we'll need to update it anytime the jupyter UI is changed, which sounds straight forward, but means that you'll have to be constantly monitoring it for changes.

**Comment by c-martinez** [comment]
We are moving to Spyder anyway, right? So all the Jupyter references can be removed (which is a shame, because I am a big fan of Jupyter notebooks...). The idea of using Spyder was exactly what you are saying @elliewix : the cognitive load of Jupyter might be too much to add on top of all that is already in the lesson.

**Comment by richyvk** [comment]
Closing due to move away form Jupyter.
